## Numpy pandas Matplotlib

## NUMPY

In [3]:
import numpy as np
array_1d=np.array([2,5,6,89,8])
print(array_1d)
print(type(array_1d))

[ 2  5  6 89  8]
<class 'numpy.ndarray'>


In [4]:
array_2d=np.array([[2,3,4],[5,5,6]])
print(array_2d)

[[2 3 4]
 [5 5 6]]


In [6]:
li=[5,6,8,8,9]
array=np.array(li)

In [7]:
print(array)

[5 6 8 8 9]


In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
array2=np.arange(15)

In [10]:
array3=array2.reshape(3,5)

In [11]:
print(array3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
array2=np.arange(10)

In [13]:
array3=array2.reshape(2,5)
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
array3[0,2]

2

In [15]:
array3[1,2]

7

In [16]:
array3[::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [17]:
array4=np.arange(20).reshape(2,5,2)
print(array4)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [18]:
array4=np.arange(10).reshape(2,5)

In [19]:
array3+array4

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [20]:
array3/array4

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [21]:
array4+5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
print(np.sin(array4))

[[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]]


In [23]:
print(np.cos(array4))

[[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]]


In [24]:
print(np.sqrt(array4))

[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]]


In [25]:
print(np.log(array4))

[[      -inf 0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [26]:
array5=np.arange(30).reshape(5,6)
print(array5)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [27]:
array5+6

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [28]:
a=(np.sqrt(array5))
print(a)

[[0.         1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479]
 [3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563]
 [4.24264069 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152]
 [4.89897949 5.         5.09901951 5.19615242 5.29150262 5.38516481]]


In [29]:
print(np.cos(a))

[[ 1.          0.54030231  0.15594369 -0.16055654 -0.41614684 -0.61727288]
 [-0.76990573 -0.87956873 -0.95136313 -0.9899925  -0.99978607 -0.98472094]
 [-0.9484432  -0.89428806 -0.82529906 -0.74424627 -0.65364362 -0.55576539]
 [-0.45266186 -0.34617416 -0.23794839 -0.129449   -0.02197145  0.08334575]
 [ 0.18550967  0.28366219  0.37706981  0.46511405  0.54728232  0.62315934]]


In [30]:
print(np.sin(a))

[[ 0.          0.84147098  0.98776595  0.98702664  0.90929743  0.78674913]
 [ 0.63815764  0.47577184  0.30807174  0.14112001 -0.02068353 -0.17413978]
 [-0.31694716 -0.44749175 -0.5646959  -0.6679053  -0.7568025  -0.83133918]
 [-0.89168225 -0.93817027 -0.9712778  -0.99158608 -0.9997586  -0.99652069]
 [-0.98264244 -0.95892427 -0.92618484 -0.88525077 -0.83694807 -0.7820949 ]]


In [31]:
print(np.log(a))

[[      -inf 0.         0.34657359 0.54930614 0.69314718 0.80471896]
 [0.89587973 0.97295507 1.03972077 1.09861229 1.15129255 1.19894764]
 [1.24245332 1.28247468 1.31952866 1.3540251  1.38629436 1.41660667]
 [1.44518588 1.47221949 1.49786614 1.52226122 1.54552123 1.56774711]
 [1.58902692 1.60943791 1.62904827 1.64791843 1.66610226 1.68364791]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [32]:
n=int(input())
def isprime(n):
    count=o
    for i in range(1,n+1):
        if n % i==0:
            count+=1
        if count==2:
            return True
def primefactor(n):
    for j in range(2,n+1):
        if isprime(j):
            print(j,end=" ")
            
primefactor(9)
        

ValueError: invalid literal for int() with base 10: ''

## KLARGEST PROGRAMS

In [33]:
def secondLargest(li):
    # Construct the list into a unique list
    # O(n)
    unique = []
    freq = {}
    for n in li:
        if n not in unique:
            unique.append(n)
            
    unique = sorted(unique,reverse=True)
    if len(unique) > 1:
        return unique[1]
    return -1

secondLargest([1])

# def fifthLeast(li)

-1

In [34]:
def fifthLargest(li):
    # Construct the list into a unique list
    # O(n)
    li=[1,5,5,9,2,5,7,3,5]
    unique = []
    freq = {}
    for n in li:
        if n not in unique:
            unique.append(n)
            
    unique = sorted(unique,reverse=True)
    if len(unique) > 4:
        return unique[1]
    return -1

fifthLargest([1,5,5,9,2,5,7,3,5])

7

In [35]:
# def kLargest(li, k)

def klargest(li, k):
    unique = []
    for i in li:
        if i not in unique:
            unique.append(i)
    unique = sorted(unique,reverse=True)
    if len(unique) >= k:
        return unique[k-1]
    return -1
klargest([], 1)

-1

In [36]:
# def kLargest(li, k)

def ksmallest(li, k):
    li=[10,20,30,40,50]
    unique = []
    for i in li:
        if i not in unique:
            unique.append(i)
    unique = sorted(unique)
    if len(unique) >= k:
        return unique[k-1]
    return -1
ksmallest([], 1)

10

In [37]:
#Function to identify the element with high frequency in a list
#If element have the highest frequency
#highestFrequencyelements[1,2,3,9,8,7,3,4,2,1]->1
def highestfrequencyelement(li):
   #Extracting unquie element with frequencises
   unique ={}
   for n in li:
       if n in unique:
           unique[n] += 1
   else:
       unique[n]=1
#unique ={1:2,2:2,3:2,9:1,8:1,7:1,4:1}
   maxfreq= max(unique.values())
   #Extract all keys with maxfreq in a list
   maxfreqkeys =[]
   for item in unique.items():
       #item ->(keys,values)
       # item[1]
       if item[1]== maxfreq:
           maxfreqkeys.append(item[0])
   return min(maxfreqkeys)
highestfrequencyelement([1,2,3,4,5,6,7,8,1])

1

In [38]:
# Function to identify second highest frequency element
# If there are many such elements, return the smallest
# [1,2,3,2,1,4,4,9] -> 3

In [39]:
#problem: special number
# Aspecial number is defined as a number which as a least, p-distinct prime number
# write a program to determine whether a number n is a special number
# i/p:p second line :t (number of test cases) Next t lines:N
# o/p:for each test case,print yes or no depending on the result

In [40]:
#Function to check if number is prime
def  isSpecialNumber(n, p):
    if numberOfPrimeFactors(n) >=p:
        return True
    return False
def isPrime(n):
    flag = 1
    if n == 2:
        return True
    for i in range(2, n//2 +1):
        if n % i == 0:
            flag = 0
            return False
    if flag == 1:
        return True
    
#Function to determine number of prime factors for a given number

def numberOfPrimeFactors(n):
    if isPrime(n):
        return 1
    count=0
    for i in range(2, n // 2 +1):
        if isPrime(i) and n % i == 0:
            count +=1
    return count

def Solution2():
    p = int(input())
    t =int(input())
    for i in range(0 ,t):
        n = int(input())
        if isSpecialNumber(n ,p):
            print("Yes")
        else:
            print("No")
isSpecialNumber(30 ,2)
    

True

In [41]:
#Function to check if number is prime
def  isSpecialNumber(n, p):
    if numberOfPrimeFactors(n) >=p:
        return True
    return False
def isPrime(n):
    flag = 1
    if n == 2:
        return True
    for i in range(2, n//2 +1):
        if n % i == 0:
            flag = 0
            return False
    if flag == 1:
        return True
    
#Function to determine number of prime factors for a given number

def numberOfPrimeFactors(n):
    if isPrime(n):
        return 1
    count=0
    for i in range(2, n // 2 +1):
        if isPrime(i) and n % i == 0:
            count +=1
    return count

def Solution2():
    p = int(input())
    t =int(input())
    for i in range(0 ,t):
        n = int(input())
        if isSpecialNumber(n ,p):
            print("Yes")
        else:
            print("No")
isSpecialNumber(16 ,2)
    

False