## SERIES AND PANDAS

In [2]:
import pandas as pd
#Series #(onedimentional array index and values)
#Dataframe #(two dimentoinal array rows and columns)

In [3]:
import pandas as pd
data=pd.Series([1,2,3,4])
data

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
import numpy as np
import pandas as pd
data=pd.Series([1,2,3,4])
data

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
data.values

array([1, 2, 3, 4], dtype=int64)

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
data[0]

1

In [8]:
data.index[0]

0

In [10]:
data[0:2] #using index slicing

0    1
1    2
dtype: int64

In [11]:
data=pd.Series([1,2,3,4,5],index=('a','b','c','d','e'))
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [12]:
data['c']

3

In [13]:
data.index[2]

'c'

In [14]:
data=pd.Series({'s':20,'a':30,'m':40,"e":50})
data

s    20
a    30
m    40
e    50
dtype: int64

In [15]:
data.values

array([20, 30, 40, 50], dtype=int64)

In [16]:
data[0]

20

In [17]:
data.index[0]

's'

In [18]:
data['s']

20

In [19]:
data[0:3]

s    20
a    30
m    40
dtype: int64

In [20]:
data['s':'m']

s    20
a    30
m    40
dtype: int64

In [21]:
data1=pd.Series(['a','b','c','d'],index=('4','6','8','10'))
data1

4     a
6     b
8     c
10    d
dtype: object

In [22]:
data1.values

array(['a', 'b', 'c', 'd'], dtype=object)

In [23]:
data1.index[0]

'4'

In [24]:
data1.index[0:3]

Index(['4', '6', '8'], dtype='object')

## DATAFRAMES

In [26]:
##DataFrames
##2-dimentional array

In [27]:
d1=pd.Series({'a':20,'b':30,'c':40})
d1

a    20
b    30
c    40
dtype: int64

In [28]:
d2=pd.Series({'a':70,'b':80,'c':120})
d2

a     70
b     80
c    120
dtype: int64

In [29]:
data=pd.DataFrame({'d1':d1,'d2':d2})
data

d1   d2
a  20   70
b  30   80
c  40  120

In [30]:
data.index

Index(['a', 'b', 'c'], dtype='object')

In [31]:
data.values

array([[ 20,  70],
       [ 30,  80],
       [ 40, 120]], dtype=int64)

In [32]:
data['d1']

a    20
b    30
c    40
Name: d1, dtype: int64

In [33]:
data['d2']

a     70
b     80
c    120
Name: d2, dtype: int64

In [34]:
d=pd.Series({'m':30,'a':40,'d':50})
d

m    30
a    40
d    50
dtype: int64

In [35]:
d3=pd.Series({'m':60,'a':10,'d':20})
d3

m    60
a    10
d    20
dtype: int64

In [36]:
data=pd.DataFrame({'d':d,'d3':d3})
data

d  d3
m  30  60
a  40  10
d  50  20

In [37]:
#Index
ind=pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [38]:
ind[1]

3

In [39]:
ind[1:3]

Int64Index([3, 5], dtype='int64')

In [40]:
print(ind.size,ind.shape,ind.ndim,ind.dtype)

5 (5,) 1 int64


In [41]:
ind[1]=0 #here values can not be change in list is immutable means we can not change values and add values

TypeError: Index does not support mutable operations

## INDEX OBJECTS ORDERED USING SETS OPERATIONS¶

In [43]:
indA=pd.Index([1,2,3,4,5])
indB=pd.Index([4,5,6,7,8])
indA & indB

Int64Index([4, 5], dtype='int64')

In [44]:
indA ^ indB

Int64Index([1, 2, 3, 6, 7, 8], dtype='int64')

In [45]:
indA | indB

Int64Index([1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [46]:
indA ^ indB

Int64Index([1, 2, 3, 6, 7, 8], dtype='int64')

In [47]:
data=pd.Series({'a':10,'b':20,'c':30})
data

a    10
b    20
c    30
dtype: int64

In [48]:
data['a']

10

In [49]:
'a' in data

True

In [50]:
data.keys()

Index(['a', 'b', 'c'], dtype='object')

In [51]:
data['a']=0.2
data

a     0
b    20
c    30
dtype: int64

In [52]:
list(data.items())

[('a', 0), ('b', 20), ('c', 30)]

In [53]:
## Slicing by explicit Indexing
data['a':'c']

a     0
b    20
c    30
dtype: int64

In [54]:
## Slicing by impicit Indexing
data[0:2]

a     0
b    20
dtype: int64

In [55]:
##Masking
data[(data>0)&(data<=20)]

b    20
dtype: int64

In [56]:
#Fancy indexing
data[['a','c']]

a     0
c    30
dtype: int64

In [57]:
## loc, iloc

In [58]:
#loc attribut allows always explicit indexing
data.loc['a':'c']

a     0
b    20
c    30
dtype: int64

In [59]:
#iloc allows implicit indexing
data.iloc[0:3]

a     0
b    20
c    30
dtype: int64

In [60]:
area=pd.Series({'california':2020,'argentina':2019,'india':2016})
population=pd.Series({'california':2016,'argentina':2014,'india':2017})
df=pd.DataFrame({'area':area,'population':population})

In [61]:
df

area  population
california  2020        2016
argentina   2019        2014
india       2016        2017

In [62]:
df['area']

california    2020
argentina     2019
india         2016
Name: area, dtype: int64

In [63]:
df.area[0]

2020

In [64]:
df.index[0]

'california'

In [65]:
area=pd.Series({'california':2020,'argentina':2019,'india':2016})
population=pd.Series({'california':2016,'argentina':2014,'india':2017,'australla':2017})
df=pd.DataFrame({'area':area,'population':population})

In [66]:
df

area  population
argentina   2019.0        2014
australla      NaN        2017
california  2020.0        2016
india       2016.0        2017